# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Callum .NET

on:
  push:
    branches: [ "Callum-Team8" ]
  pull_request:
    branches: [ "Callum-Team8" ]

env:
  registryName: 7i5crswc5yo2gwthreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Docker build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
      
    - name: Docker push
      run: docker push $registryName/$repositoryName:$tag

    - name: Docker deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: '7i5crswc5yo2g-dev'
        images: 7i5crswc5yo2gwthreg.azurecr.io/wth/dotnetcoreapp:$tag'
      

      
      
    
