name: .NET

on:
  push:
    paths:
      - 'Application/**' # Trigger only for changes in the /Application folder
    branches:
      - main
  pull_request:
    paths:
      - 'Application/**' # Trigger only for changes in the /Application folder
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check .NET Version
      run: |
        dotnet_version=$(dotnet --version)
        if [[ "$dotnet_version" != "6.0."* ]]; then
          echo "Error: This workflow requires .NET 6.0.x. Found version: $dotnet_version"
          exit 1
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --project ./Application/Application.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/Application.csproj
