name: Deepraj .NET Build

on:
  push:
    paths:
      - 'Application/**' # Trigger only for changes in the /Application folder
    branches:
      - main
  pull_request:
    paths:
      - 'Application/**' # Trigger only for changes in the /Application folder
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --project ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Create GitHub Issue on Failure
      if: ${{ steps.deployment_status.outputs.status == 'failure' }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: createIssueResponse } = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Deployment Failed',
            body: 'The deployment to Azure failed. Please investigate and fix the issue.',
          });
          console.log(`Created issue ${createIssueResponse.number}`);
