name: Docker Image CI - Priyanshi

on:
  push:
    branches: [ "Priyanshi" ]
  pull_request:
    branches: [ "Priyanshi" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login To Azure Container Registry
    - uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: docker build --file ./Application/src/RazorPagesTestSample/Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/priyanshi-image ./Application/src/RazorPagesTestSample
    - name: Run the Docker Image 
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/priyanshi-image
