name: Johan Docker Image CI

on:
  push:
    branches: [ "johan" ]
  pull_request:
    branches: [ "johan" ]

env:
  tag: ${{ github.run_number }}
  repo: johans-repo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: docker build --file ./Application/src/RazorPagesTestSample/Dockerfile --build-arg build_version=$tag --tag ${{ secrets.ACR_LOGIN_SERVER }}/$repo:$tag ./Application/src/RazorPagesTestSample
    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/$repo:$tag
