name: Johan Docker Image CI

on:
  push:
    branches: [ "johan" ]
  pull_request:
    branches: [ "johan" ]

env:
  tag: ${{ github.run_number }}
  repo: johans-repo
  appname: 7i5crswc5yo2g-prod

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build the Docker image
      run: docker build --file ./Application/src/RazorPagesTestSample/Dockerfile --build-arg build_version=$tag --tag ${{ secrets.ACR_LOGIN_SERVER }}/$repo:$tag ./Application/src/RazorPagesTestSample
    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/$repo:$tag
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v3.0.0
      with: 
        app-name: 7i5crswc5yo2g-prod
        images: 7i5crswc5yo2gwthreg.azurecr.io/johans-repo:${{ env.tag }}
    
