name: shiva-deploy-workflow
run-name: ${{ github.actor }} is testing out GitHub Actions For Deploying 🚀
on: workflow_dispatch 
jobs:
  Explore-GitHub-Actions-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
   

