name: Shiva Docker Image CI

on:
  push:
    branches: [ "team8-shiva" ]
  pull_request:
    branches: [ "team8-shiva" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: docker build --file ./Application/src/RazorPagesTestSample/Dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/johans-image ./Application/src/RazorPagesTestSample
    - name: Push Docker image
      run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/Shiva-image
